#!groovy

node {
    currentBuild.result = "SUCCESS"
    env.CI = "true"
    try {
       stage('Checkout'){
          checkout scm
       }

       stage('BuildAndTest'){
          sh 'docker build -t richardzone/quokka-test-awesome-image .'
          sh 'docker run --rm richardzone/quokka-test-awesome-image npm test'
       }

       stage('DeployToDev'){
          sh 'docker run -d -p 3001:3000 richardzone/quokka-test-awesome-image'
       }

       stage('DeployToTest'){
          sh 'docker run -d -p 3002:3000 richardzone/quokka-test-awesome-image'
       }

       stage('DeployToProd'){
          sh 'docker run -d -p 3003:3000 richardzone/quokka-test-awesome-image'
       }


    }
    catch (err) {
        currentBuild.result = "FAILURE"
        throw err
    }

}
